### ISSUE TITLE
Proposal: rewrite of What to do when your team has imposter syndrome

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization-ambassadors/open-org-it-culture#18]
I thought a rewrite of the article i recently wrote for opensource.com might be appropriate for the "Skills" section? We might re-title it to something like "Avoiding Semantic Traps in Project Management"?

**Comment by semioticrobotic** [comment]
Totally, @LauraHilliger. I think that'd be a great fit. Let's you and I revisit the writing and see if there are any tweakable moments we can adapt for the IT crowd. It will not be difficult!

**Comment by semioticrobotic** [comment]
Okay, so, @LauraHilliger, I re-read the piece in its current form and I really think it needs very _little_ in order to fit the volume. It reads quite accessibly as-is, even for the relatively different audience. Should you _have_ one or two ideas for working in IT-specific language or examples, then of course we're all for that! But if you'd like to run right ahead, I think we can make it work in its current form. At the very least, I can put it into production and you can have a look.

**Comment by LauraHilliger** [comment]
hey! Sorry for my slacking on this. I reread the piece and think it's general enough in it's language too. I wouldn't change anything for the IT crowd – they work with PMs and planning committees and stuff too!

**Comment by semioticrobotic** [comment]
Hey, no worries! Glad you agree. I'll get to work on it right away and incorporate it into an upcoming code push, so you can see how it will look when typeset. If at that point you notice anything you'd like to change, just holler.

**Comment by semioticrobotic** [comment]
This chapter has now been typeset! Thanks (and congrats) @LauraHilliger!
