### ISSUE TITLE
Write a chapter on mirroring (personalities)

### ISSUE THREAD

**Issue by knitterb** [open-organization-ambassadors/open-org-it-culture#5]
This would be a chapter dedicated to the discussion of how to mirror personalities in order to get the most from an inter-personal effort or relationship.  Ideas, suggestions and examples will be used to demonstrate how to mirror a personality, and the various personalities I've come across.

As a designer, I find that getting the most from the person I'm working with is both personal and unique.  Learning to mirror the individual's personality doesn't just soften the discussion, but it makes the interaction much more productive.

Whether working with someone who is extremely introverted, or someone who is much more extroverted and animated, harnessing my counterpart's positive personality traits enables a stronger relationship.  Not everyone wants to talk, not everyone wants to work at a whiteboard, not everyone wants to sit idly and watch a conversation.  Engagement is key, and doing it the right way is critical!

Background: https://en.wikipedia.org/wiki/Mirroring_(psychology)

**Comment by knitterb** [comment]
I'd like to write this!

**Comment by semioticrobotic** [comment]
We'd love to read this proposal, @knitterb, as long as it's explicitly tied to IT organizations and offers actionable tips for folks working in them.

**Comment by knitterb** [comment]
What is the preferred format for a proposal?  An outline, an abstract, a summary, or the entire contents?

**Comment by semioticrobotic** [comment]
The simplest answer is: Any of the above! If you'd like to send (or post) an abstract or outline for review, then we can begin there. But if this is already something you've drafted, we'll gladly review that draft with you, too.

**Comment by knitterb** [comment]
Please note that this is intended for the "skills" section of the book?
(not sure if there is a label for this)

Abstract and outline coming...

**Comment by knitterb** [comment]
# Abstract (or maybe Intro)
For years, IT organizations have been the focus of much needed technology innovation.  From high-tech advancements to cost savings, the modern IT organization has traditionally been a place solely for technologists.  This landscape is changing as cultures from around the world gather to solve some of the world’s toughest and largest problems.  

With these new cultures come a widely varied set of beliefs and ultimately decisions are made based upon individual desires that must somehow capture the needs of the organization.  In an age where nearly anyone can learn technology, from software development to large scale systems administration, this diverse set of personalities is a cacophony of background and experience.

Interaction styles have also evolved.  Ever present changes to online and in-person communications have given nearly every personality the right tool for their individual needs.  From chalk boards to whiteboards, phones to video conferencing, and instant messaging to private group forums, the way we communicate has changed dramatically in just the last 15 years.  And still, the driving force behind these IT organizations are humans that must interact and collaborate in order achieve the challenges that lie ahead.

When working between individuals, common ground must go well beyond the undeniable facts.  People must communicate with people.  The only way to have two or more drastically different personalities meld is to find the common ground of personalities.  Whether it be an agreed means of communication, the framework of communications, or the cadence of communications; this common ground, in many cases, solves for a least common denominator that extracts less than the full potential each individual has within, and the whole becomes less than the sum of its parts. 

One can achieve a common ground much more quickly by selecting people with similar (or complementing) personalities.  In cases where the personalities work well together, the productivity gains are enormous.  The opposite is sometimes quite dramatic and appalling.  But finding these people with similar personalities traits has become harder for an industry that, while more progress is required, does enjoy a good amount of diversity.

One mechanism for increasing the likelihood of compatibility between two people is to simply concede.  By adapting to a counterpart’s personality and adopting their traits, two colleagues can quickly reach a similar means of communication and begin to solve the issue at hand.

Most commonly implemented by those that facilitate discussions either for themselves or others, the psychological phenomenon called “mirroring” is a strategy as much as it is a subconscious result of a millennium of brain evolution.  Practiced intentionally, this so-called “active mirroring” technique is quite effective when attempting to extract ideas or overcome a project roadblock.  No matter the application, active mirroring results in a much more fruitful outcome for the individuals as much as the corporation they serve. 

Active mirroring can be applied to many scenarios including those that involve more than two participants.  Whether in a design session, troubleshooting, or status report; active mirroring requires one participant to observe, understand and then implement the traits of their counterpart.  From speaking cadence to word usage to communications preferences, this common ground provides a tremendous benefit both to the project and to the relationship.

**Comment by semioticrobotic** [comment]
Thanks for laying this out, @knitterb. It's an interesting topic, to be sure. A few notes:

1. I think the chapter really hits its stride in the third paragraph above. I'd recommend simply beginning a prospective chapter there.

2. You write:

> One can achieve a common ground much more quickly by selecting people with similar (or complementing) personalities. In cases where the personalities work well together, the productivity gains are enormous. The opposite is sometimes quite dramatic and appalling. But finding these people with similar personalities traits has become harder for an industry that, while more progress is required, does enjoy a good amount of diversity.

The relationship between diversity (of background, of talent(s), of thought, of work style, etc.) and mirroring seems like it will be central to a chapter like this one. I think readers will want to know how mirroring affects a given team's dynamic, especially if that team intentionally composed itself of individuals with diverse and divergent backgrounds and styles in order to reap the benefits it sees in heterogeneity. In your initial query, you write that "... not everyone wants to talk, not everyone wants to work at a whiteboard, not everyone wants to sit idly and watch a conversation." What would you say to someone who claims that practicing mirroring actually encourages people to deliberately adopt practices that don't resemble their preferences (e.g., work at a whiteboard when that's not my style but is what my partner prefers, watch a conversation when that's not my style but is what my prefers, and so on).

3. I'm especially interested in the section that addresses active mirroring's benefits to teams in IT organizations, "whether in a design session, troubleshooting, or status report." I think the chapter could demonstrate mirroring's benefits by showing readers precisely how it functions in the context of one or two of these projects. As this is the "Skills" section of the book, the focus is on practical and actionable descriptions of behaviors readers can adopt to change the way they work.

4. Keep in mind that the average length of a submission is 800 and 1000 words. Longer is fine in certain circumstances, but we'll need to remain rigorous.

**Comment by knitterb** [comment]
Great feedback and I agree with your points. I can certainly tighten this
up, and I was planning to go into specifics, I've just run out of time this
weekend.

Since I'm a little late in my proposal, and the deadline is tomorrow, what
do you see as the next steps for helping you make a determination for a
chapter on Mirroring?

**Comment by semioticrobotic** [comment]
How about we move to an outline next. You're welcome to compose it in any way you'd like; just share with me at bbehrens@redhat.com and we'll go from there. This'll help get a good sense of the scope, I think!

**Edit:** By the way, if you aren't able to do this by tomorrow, then please don't worry! We can examine over the next few days. Just happy to have the ball rolling.

**Comment by knitterb** [comment]
I will work on this outline tonite and get it to you tomorrow!
